AWSTemplateFormatVersion: 2010-09-09

Description: |
  Kitten Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.

Resources:
  ArifCFNInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey 
      SecurityGroups: 
        - MyFirstSecGroup
      Tags:
        - Key: Name
          Value: ArifCfnInstance 
      UserData: 
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 var/www/html
          cd var/www/html
          wget https://github.com/arifzengin/Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/blob/main/static-web/index.html
          wget https://github.com/arifzengin/Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/blob/main/static-web/cat0.jpg
          wget https://github.com/arifzengin/Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/blob/main/static-web/cat1.jpg
          wget https://github.com/arifzengin/Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/blob/main/static-web/cat2.jpg
          wget https://github.com/arifzengin/Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/blob/main/static-web/cat3.png
          
